"use client";

import { atom } from "jotai";

export const gameScoreLeftAtom = atom(0);
export const gameScoreRightAtom = atom(0);
export const totalBreakLeftAtom = atom(0);
export const totalBreakRightAtom = atom(0);
export const winningStreakLeftAtom = atom(0);
export const winningStreakRightAtom = atom(0);
export const ballsPocketedLeftAtom = atom(0);
export const ballsPocketedRightAtom = atom(0);
export const ballsMissedLeftAtom = atom(0);
export const ballsMissedRightAtom = atom(0);
export const ballsMissedWithSafetyLeftAtom = atom(0);
export const ballsMissedWithSafetyRightAtom = atom(0);
export const unforcedErrorsLeftAtom = atom(0);
export const unforcedErrorsRightAtom = atom(0);
export const safetyErrorsLeftAtom = atom(0);
export const safetyErrorsRightAtom = atom(0);
export const kickingErrorsLeftAtom = atom(0);
export const kickingErrorsRightAtom = atom(0);
export const dryBreaksLeftAtom = atom(0);
export const dryBreaksRightAtom = atom(0);
export const scratchesonBreakLeftAtom = atom(0);
export const scratchesonBreakRightAtom = atom(0);
export const ballsMadeonBreakLeftAtom = atom(0);
export const ballsMadeonBreakRightAtom = atom(0);
export const shotAfterTheBreakLeftAtom = atom(0);
export const shotAfterTheBreakRightAtom = atom(0);
export const consecutiveBreakandRunsLeftAtom = atom(0);
export const consecutiveBreakandRunsRightAtom = atom(0);
export const breakAndRunLeftAtom = atom(0);
export const breakAndRunRightAtom = atom(0);
